onboarding = false

[terminal]
default_shell = "fish"

[theme]
name = "tokyo-night"
auto_switch = false

[ui]
status_indicators = "symbols"
window_title = "herdr · {workspace}"
mouse_capture = false

[ui.toast]
delivery = "herdr"

[experimental]
allow_nested = true
