import = ["/Users/jonas-mika/.config/alacritty/colors/rose-pine.toml"]
live_config_reload = true
working_directory = "None"


[window]
decorations = "None"
dynamic_padding = false
opacity = 0.97
padding = { x = 10, y = 10 }

[font]
size = 20.0
normal = { family = "Hack Nerd Font Mono" }
bold = { family = "Hack Nerd Font Mono" }
italic = { family = "Hack Nerd Font Mono" }

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { action = "Paste", key = "V", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },
  { action = "Quit", key = "Q", mods = "Command" },
  { action = "IncreaseFontSize", key = "Plus", mods = "Command" },
  { action = "DecreaseFontSize", key = "Minus", mods = "Command" },
  { action = "ResetFontSize", key = "Key0", mods = "Command" },
  { chars = "\u0001\"", key = "D", mods = "Command" },
  { chars = "\u0001%", key = "D", mods = "Command|Shift" },
  { chars = "\u0001h", key = "H", mods = "Command" },
  { chars = "\u0001j", key = "J", mods = "Command" },
  { chars = "\u0001k", key = "K", mods = "Command" },
  { chars = "\u0001l", key = "L", mods = "Command" },
  { chars = "\u0001c", key = "T", mods = "Command" },
  { chars = "\u0001x", key = "W", mods = "Command" },
  { chars = "\u0001p", key = "J", mods = "Command|Shift" },
  { chars = "\u0001n", key = "K", mods = "Command|Shift" },
  { chars = "\u0001f", key = "F", mods = "Command" },
  { chars = "\u0001o", key = "O", mods = "Command" },
  { chars = "\u0001i", key = "I", mods = "Command" },
  { chars = "\u0001L", key = "L", mods = "Command|Shift" },
  { chars = "\u0001z", key = "P", mods = "Command" },
  { chars = "\u0001H", key = "Left", mods = "Command" },
  { chars = "\u0001J", key = "Down", mods = "Command" },
  { chars = "\u0001K", key = "Up", mods = "Command" },
  { chars = "\u0001L", key = "Right", mods = "Command"},
  { chars = "\u0001", key = "A", mods = "Control" },
  { chars = "\u0002", key = "B", mods = "Control" },
  { chars = "\u0003", key = "C", mods = "Control" },
  { chars = "\u0004", key = "D", mods = "Control" },
  { chars = "\u0005", key = "E", mods = "Control" },
  { chars = "\u0006", key = "F", mods = "Control" },
  { chars = "\u0007", key = "G", mods = "Control" },
  { chars = "\b", key = "H", mods = "Control" },
  { chars = "\t", key = "I", mods = "Control" },
  { chars = """

""",key = "J", mods = "Control" },
  { chars = "\u000B", key = "K", mods = "Control" },
  { chars = "\f", key = "L", mods = "Control" },
  { chars = "\r", key = "M", mods = "Control" },
  { chars = "\u000E", key = "N", mods = "Control" },
  { chars = "\u000F", key = "O", mods = "Control" },
  { chars = "\u0010", key = "P", mods = "Control" },
  { chars = "\u0011", key = "Q", mods = "Control" },
  { chars = "\u0012", key = "R", mods = "Control" },
  { chars = "\u0013", key = "S", mods = "Control" },
  { chars = "\u0014", key = "T", mods = "Control" },
  { chars = "\u0015", key = "U", mods = "Control" },
  { chars = "\u0016", key = "V", mods = "Control" },
  { chars = "\u0017", key = "W", mods = "Control" },
  { chars = "\u0018", key = "X", mods = "control" },
  { chars = "\u0019", key = "Y", mods = "Control" },
  { chars = "\u001A", key = "Z", mods = "Control" },
]

